push digest

diff --git a/.github/actions/publish-image/action.yaml b/.github/actions/publish-image/action.yaml
--- a/.github/actions/publish-image/action.yaml
+++ b/.github/actions/publish-image/action.yaml
@@ -55,7 +55,16 @@ runs:
       COSIGN_REPOSITORY: ${{ inputs.sbom-repository }}
     run: |
       set -e
-      echo "digest=$(VERSION=${{ inputs.version }} make ${{ inputs.makefile-target }})" >> $GITHUB_OUTPUT
+      OUTPUT=$(VERSION=${{ inputs.version }} make ${{ inputs.makefile-target }} | tee /dev/stderr)
+      DIGEST=$(echo "$OUTPUT" | grep -Eo 'sha256:[a-f0-9]{64}' | head -n 1)
+
+      if [ -z "$DIGEST" ]; then
+        echo "ERROR: Failed to extract digest from ko output." >&2
+        exit 1
+      fi
+
+      # Write the digest to GITHUB_OUTPUT
+      echo "digest=$DIGEST" >> $GITHUB_OUTPUT
   - uses: CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f # v1.1.0
     with:
       version: v1
